Feature/encapsulation
sonia-auv/proc_image_processing pull request #32
Opened 2021-06-27 03:46 UTC by ProgHunter

## Description
Ensure all class attributes are private and have accessors if needed.

## Fixes
Link all the related issues from the issue tracker
- Closes: #31 

## How has this been tested ?
- Tested locally by building and running it

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-06-27 19:05 UTC, willDBZ requested changes, later dismissed
looks good to me

2021-06-27 19:05 UTC, willDBZ commented on src/proc_image_processing/algorithm/general_function.h
> -  float CalculatePourcentFilled(const cv::Mat& image,
Renommer la fonction: CalculatePercentFilled.

2021-06-27 19:05 UTC, willDBZ commented on src/proc_image_processing/filters/detectors/pipe_angle_detector.h
>  /// \author	Jérémie St-Jules Prévôt <jeremie.st.jules.prevost@gmail.com>
Enlever les sections \author aussi?

2021-06-28 18:39 UTC, ProgHunter commented on src/proc_image_processing/filters/detectors/pipe_angle_detector.h
>  /// \author	Jérémie St-Jules Prévôt <jeremie.st.jules.prevost@gmail.com>
Suivant les exigences de la tâche "NF-1.4 Nettoyage du repo" seul les champs author et date ont été gardés pour l'entête des fichiers.

2021-06-28 19:24 UTC, ProgHunter commented on src/proc_image_processing/algorithm/general_function.h
> -  float CalculatePourcentFilled(const cv::Mat& image,
Done!

2021-07-16 14:17 UTC, Ismedrasor approved these changes
Modification have been approve, @willDBZ can you close your change request?

2021-07-16 14:57 UTC, Ismedrasor approved these changes

2021-07-16 14:58 UTC, merged