Feature/refactoring
sonia-auv/proc_image_processing pull request #35
Opened 2021-07-03 20:35 UTC by willDBZ

**Warning :** Before creating a pull request, make sure that it does not already exists in the [pull requests](../). Thank you.

## Description
Removed the variable "enable_" in all the filters and detectors. The logic to check if the filter is enabled before executing it is now done in the parent class, which is the class Filter.

## Fixes
Link all the related issues from the issue tracker
- Closes: #

## How has this been tested ?
Compile the code and see if it generates any errors.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-07-08 03:28 UTC, ProgHunter requested changes
The branch should be merged in develop, not master. 
Otherwise, good refactoring of "enable_". 👍

2021-07-08 15:10 UTC, thecanadianroot requested changes

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/adaptive_threshold.h
> +    void ApplyFilter(cv::Mat& image) {
Je changerais pour apply(cv::Mat& image). L'object est un filter, pas besoin de préciser qu'on ApplyFilter, juste apply c'est suffisant. Généralement quand on va instancier notre filter, la variable risque de se nommer filterQuelqueChose, donc quand on fait filterQuelqueChose->apply() ça fait plus de sens que filterQuelqueChose->ApplyFilter(). Aussi pourquoi le first letter est capital ? les fonctions devrait pas starter en minuscules pour réserver ça aux classes?

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/background_substract.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/bilateral_filter.h
> +    void ApplyFilter(cv::Mat& image) override {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/blurr.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/canny.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/contrast_brightness.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/convex_hull.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/deep_2019.h
> +        virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/center_coffin_detector.h
> +        virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/fence_detector.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/gate_detector.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/handle_detector.h
> +    virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/pipe_angle_detector.h
> +        virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/vampire_body_detector.h
> +        virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/vampire_torpedoes_close_detector.h
> +        virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 15:10 UTC, thecanadianroot commented on src/proc_image_processing/filters/detectors/vampire_torpedoes_detector.h
> +        virtual void ApplyFilter(cv::Mat& image) {
Same

2021-07-08 16:34 UTC, thecanadianroot requested changes

2021-07-08 16:34 UTC, thecanadianroot commented on src/proc_image_processing/filters/adaptive_threshold.h
> +    void ApplyFilter(cv::Mat& image) {
Aussi, voir code smell de sonarcloud: https://sonarcloud.io/project/issues?branch=feature%2Frefactoring&id=sonia-auv_proc_image_processing&issues=AXpt9H0jxl0da__V49lY&open=AXpt9H0jxl0da__V49lY

2021-07-12 14:38 UTC, willDBZ commented on src/proc_image_processing/filters/adaptive_threshold.h
> +    void ApplyFilter(cv::Mat& image) {
Pour le nom des fonctions en PascalCalse vs camelCase, j'ai écrit un message dans Discord pour vérifier avec l'équipement de développement, car les deux façons de faire semblent correctes quoique camelCase est plus populaire.

2021-07-12 14:40 UTC, willDBZ commented on src/proc_image_processing/filters/adaptive_threshold.h
> +    void ApplyFilter(cv::Mat& image) {
Je viens de voir les updates de Alexandre sur Discord. Les fonctions seront changées en lowerCase.

2021-07-12 14:46 UTC, willDBZ commented on src/proc_image_processing/filters/adaptive_threshold.h
> +    void ApplyFilter(cv::Mat& image) {
done

2021-07-12 14:46 UTC, willDBZ commented on src/proc_image_processing/filters/background_substract.h
> +    virtual void ApplyFilter(cv::Mat& image) {
done

2021-07-19 22:48 UTC, ProgHunter commented on src/proc_image_processing/filters/hough_line.h
> +    void ApplyFilter(cv::Mat& image) {
Should we declare ApplyFilter() in filter's implementation as "final" ?

2021-07-19 22:48 UTC, ProgHunter commented on src/proc_image_processing/filters/hsv_threshold.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:50 UTC, ProgHunter commented on src/proc_image_processing/filters/image_accumulator.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:50 UTC, ProgHunter commented on src/proc_image_processing/filters/image_cropper.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:50 UTC, ProgHunter commented on src/proc_image_processing/filters/laplacian.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:50 UTC, ProgHunter commented on src/proc_image_processing/filters/mission_test_fake_string.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:50 UTC, ProgHunter commented on src/proc_image_processing/filters/morphology.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:51 UTC, ProgHunter commented on src/proc_image_processing/filters/original_image.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:51 UTC, ProgHunter commented on src/proc_image_processing/filters/remove_mask.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:51 UTC, ProgHunter commented on src/proc_image_processing/filters/rotate.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:51 UTC, ProgHunter commented on src/proc_image_processing/filters/schar_adding.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:52 UTC, ProgHunter commented on src/proc_image_processing/filters/scharr.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:52 UTC, ProgHunter commented on src/proc_image_processing/filters/sobel.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:52 UTC, ProgHunter commented on src/proc_image_processing/filters/square_detection.h
> +        virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:52 UTC, ProgHunter commented on src/proc_image_processing/filters/stats_threshold.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:52 UTC, ProgHunter commented on src/proc_image_processing/filters/submarine_frame_masker.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:52 UTC, ProgHunter commented on src/proc_image_processing/filters/subtract_all_planes.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:54 UTC, ProgHunter commented on src/proc_image_processing/filters/subtract_plane_adder.h
>      virtual void execute(cv::Mat& image) {
replace with "void ApplyFilter(cv::Mat& image) {" ?

2021-07-19 22:54 UTC, ProgHunter commented on src/proc_image_processing/filters/test_filter.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:55 UTC, ProgHunter commented on src/proc_image_processing/filters/threshold.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:55 UTC, ProgHunter commented on src/proc_image_processing/filters/threshold_between.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 22:56 UTC, ProgHunter commented on src/proc_image_processing/filters/white_filter.h
> +        virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 23:01 UTC, ProgHunter commented on src/proc_image_processing/filters/white_filter.h
> -        Parameter<bool> enable_;
The variable "enable_" was not used in this filter. We should be vigilant about its behaviour when adding the condition by calling Execute() on it. Try to verify if it works correctly with this change.

2021-07-19 23:02 UTC, ProgHunter commented on src/proc_image_processing/filters/white_noise_takedown.h
> +    virtual void ApplyFilter(cv::Mat& image) {
no virtual needed here

2021-07-19 23:03 UTC, ProgHunter requested changes
See comments :)

2021-08-06 20:29 UTC, ProgHunter commented
Since the PR relies on a too old version of 'develop', we decided to reimplement the changes from the current state of the branch, this will be way more simple to merge.

2021-08-06 20:29 UTC, closed without merging